# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e82d2ae17ec1e5497846ac0e00788f1edef29d1ac2624c085436c5ee0bad97c0ec74bae68b80b5097e26926e398b729e9d66d376bae41e804f8ce6a72ec50b61

test:
  secret_key_base: 1919be9066fa1e93f3589d03a49fd41dc105a2a1ceeac36c36edb629422487c4180ac4a1056b175e8f6ed22c32ac37a22e6d15270f23b5f9b401970c9b47a271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
